server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
      - id: evento
        uri: lb://event/
        predicates:
          - Path=/event/**
      - id: usere
        uri: lb://user/
        predicates:
          - Path=/user/**
