server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
      - id: event
        uri: lb://event/
        predicates:
          - Path=/event/**
      - id: user
        uri: lb://user/
        predicates:
          - Path=/user/**
      - id: login
        uri: lb://login/
        predicates:
          - Path=/login/**
      - id: venta
        uri: lb://venta/
        predicates:
          - Path=/venta/**
